/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionColumn: typeof import('./src/components/common/ActionColumn.vue')['default']
    BackNav: typeof import('./src/components/common/BackNav.vue')['default']
    ChangePasswordDialog: typeof import('./src/components/common/ChangePasswordDialog.vue')['default']
    ChartCard: typeof import('./src/components/common/ChartCard.vue')['default']
    DataTable: typeof import('./src/components/common/DataTable.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    FilterBar: typeof import('./src/components/common/FilterBar.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    PageShell: typeof import('./src/components/common/PageShell.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/common/StatCard.vue')['default']
    StatCardGrid: typeof import('./src/components/common/StatCardGrid.vue')['default']
    StatusTag: typeof import('./src/components/common/StatusTag.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
